directories:
  output: dist_electron
  buildResources: build
appId: com.brunojustino.syncapp
productName: DBF Sync Tool
win:
  target: nsis
  icon: public/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
files:
  - filter:
      - dist/**/*
      - package.json
publish:
  - provider: generic
    url: https://updates.brunojustino.com/sync-tool/
electronVersion: 40.0.0
